# 36協定：基本定数（特別条項なし）
MAX_DAILY_WORK_HOURS = 8  # 1日8時間
MAX_WEEKLY_WORK_HOURS = 40  # 週40時間
MAX_MONTHLY_OVERTIME_HOURS = 45  # 月45時間まで
MAX_YEARLY_OVERTIME_HOURS = 360  # 年360時間まで

# 特別条項ありの場合
SPECIAL_CLAUSE_ENABLED = True
MAX_MONTHLY_OVERTIME_WITH_CLAUSE = 100  # 単月100時間未満（休日込み）
AVG_OVERTIME_LIMIT_2_TO_6_MONTHS = 80  # 2〜6ヶ月平均80時間以内
MAX_YEARLY_OVERTIME_WITH_CLAUSE = 720  # 年720時間まで（休日込み）

# その他の関連制約
MIN_REST_INTERVAL_HOURS = 10  # 勤務終了から次勤務までのインターバル
MAX_CONSECUTIVE_WORK_DAYS = 5  # 推奨：連続勤務5日まで
